services:
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile.local
    volumes:
      - ./data/:/usr/src/quant-prophet/data/
    tty: true
    working_dir: /usr/src/qlib/
  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/src/quant-prophet/
    tty: true
    working_dir: /usr/src/quant-prophet/
